# fly.toml app configuration file generated for imagic-ink on 2026-03-10T04:06:50+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'imagic-ink'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  size = 'shared-cpu-1x'
  memory = '1gb'
